In [21]:
# ! pip install opencv-python
import cv2
import numpy as np

In [ ]:
img=cv2.imread("Dog.png") # Read the image

In [ ]:
cv2.imshow("window",img) # Show the image in a window
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img_grey=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY) # Convert the image into greyscale

In [14]:
cv2.imshow("window",img_grey)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
blur_image=cv2.GaussianBlur(img,(25,25),0) # Blurring the image

In [18]:
cv2.imshow("window",blur_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
edge=cv2.Canny(img,100,200) # Detecting edges in the image

In [20]:
cv2.imshow("window",edge)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Drawing Shapes and Text on Image

In [25]:
img_zero=np.zeros((512,512,3))

In [26]:
cv2.imshow("window",img_zero)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.rectangle(img_zero,pt1=(20,20),pt2=(80,80),color=(0,255,0),thickness=-1) # Create a rectangle 

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], shape=(512, 512, 3))

In [ ]:
cv2.circle(img_zero,center=(250,250),radius=60,thickness=5,color=(255,0,0)) # Create a circle 

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], shape=(512, 512, 3))

In [ ]:
cv2.line(img_zero,pt1=(0,0),pt2=(512,512),thickness=6,color=(0,0,255)) # Create a line

array([[[  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       ...,

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        ...,
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        ...,
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,  

In [ ]:
cv2.putText(img_zero,org=(90,90),fontScale=4,color=(255,255,255),thickness=2,lineType=cv2.LINE_AA,text="Arya",fontFace=cv2.FONT_ITALIC) # Add a text

array([[[  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       ...,

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        ...,
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        ...,
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,  

In [33]:
cv2.imshow("window",img_zero)
cv2.waitKey(0)
cv2.destroyAllWindows()